v_10 = tt.stack([math.dot(sd, ro ** 9), math.dot(sd, ro ** 8), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 6), math.dot(sd, ro ** 5),
                 math.dot(sd, ro ** 4), math.dot(sd, ro ** 3), math.dot(sd, ro ** 2),
                 math.dot(sd, ro ** 1),
                 math.dot(sd, ro ** 0), math.dot(sd, ro ** 1), math.dot(sd, ro ** 2),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 5), math.dot(sd, ro ** 6), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 8), math.dot(sd, ro ** 9),
                 math.dot(sd, ro ** 10), math.dot(sd, ro ** 11), math.dot(sd, ro ** 12),
                 math.dot(sd, ro ** 13), math.dot(sd, ro ** 14),
                 math.dot(sd, ro ** 15), math.dot(sd, ro ** 16), math.dot(sd, ro ** 17),
                 math.dot(sd, ro ** 18), math.dot(sd, ro ** 19),
                 math.dot(sd, ro ** 20), math.dot(sd, ro ** 21), math.dot(sd, ro ** 22),
                 math.dot(sd, ro ** 23), math.dot(sd, ro ** 24),
                 math.dot(sd, ro ** 25), math.dot(sd, ro ** 26), math.dot(sd, ro ** 27),
                 math.dot(sd, ro ** 28)]).reshape((l_freq,))

v_11 = tt.stack([math.dot(sd, ro ** 10), math.dot(sd, ro ** 9), math.dot(sd, ro ** 8),
                 math.dot(sd, ro ** 7), math.dot(sd, ro ** 6),
                 math.dot(sd, ro ** 5), math.dot(sd, ro ** 4), math.dot(sd, ro ** 3),
                 math.dot(sd, ro ** 2), math.dot(sd, ro ** 1),
                 math.dot(sd, ro ** 0), math.dot(sd, ro ** 1), math.dot(sd, ro ** 2),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 5), math.dot(sd, ro ** 6), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 8), math.dot(sd, ro ** 9),
                 math.dot(sd, ro ** 10), math.dot(sd, ro ** 11), math.dot(sd, ro ** 12),
                 math.dot(sd, ro ** 13), math.dot(sd, ro ** 14),
                 math.dot(sd, ro ** 15), math.dot(sd, ro ** 16), math.dot(sd, ro ** 17),
                 math.dot(sd, ro ** 18), math.dot(sd, ro ** 19),
                 math.dot(sd, ro ** 20), math.dot(sd, ro ** 21), math.dot(sd, ro ** 22),
                 math.dot(sd, ro ** 23), math.dot(sd, ro ** 24),
                 math.dot(sd, ro ** 25), math.dot(sd, ro ** 26),
                 math.dot(sd, ro ** 27)]).reshape((l_freq,))

v_12 = tt.stack([math.dot(sd, ro ** 11), math.dot(sd, ro ** 10), math.dot(sd, ro ** 9),
                 math.dot(sd, ro ** 8), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 6), math.dot(sd, ro ** 5), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 2), math.dot(sd, ro ** 1),
                 math.dot(sd, ro ** 0), math.dot(sd, ro ** 1), math.dot(sd, ro ** 2),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 5), math.dot(sd, ro ** 6), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 8), math.dot(sd, ro ** 9),
                 math.dot(sd, ro ** 10), math.dot(sd, ro ** 11), math.dot(sd, ro ** 12),
                 math.dot(sd, ro ** 13), math.dot(sd, ro ** 14),
                 math.dot(sd, ro ** 15), math.dot(sd, ro ** 16), math.dot(sd, ro ** 17),
                 math.dot(sd, ro ** 18), math.dot(sd, ro ** 19),
                 math.dot(sd, ro ** 20), math.dot(sd, ro ** 21), math.dot(sd, ro ** 22),
                 math.dot(sd, ro ** 23), math.dot(sd, ro ** 24),
                 math.dot(sd, ro ** 25), math.dot(sd, ro ** 26)]).reshape((l_freq,))

v_13 = tt.stack([math.dot(sd, ro ** 12), math.dot(sd, ro ** 11), math.dot(sd, ro ** 10),
                 math.dot(sd, ro ** 9), math.dot(sd, ro ** 8),
                 math.dot(sd, ro ** 7), math.dot(sd, ro ** 6), math.dot(sd, ro ** 5),
                 math.dot(sd, ro ** 4), math.dot(sd, ro ** 3), math.dot(sd, ro ** 2),
                 math.dot(sd, ro ** 1),
                 math.dot(sd, ro ** 0), math.dot(sd, ro ** 1), math.dot(sd, ro ** 2),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 5), math.dot(sd, ro ** 6), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 8), math.dot(sd, ro ** 9),
                 math.dot(sd, ro ** 10), math.dot(sd, ro ** 11), math.dot(sd, ro ** 12),
                 math.dot(sd, ro ** 13), math.dot(sd, ro ** 14),
                 math.dot(sd, ro ** 15), math.dot(sd, ro ** 16), math.dot(sd, ro ** 17),
                 math.dot(sd, ro ** 18), math.dot(sd, ro ** 19),
                 math.dot(sd, ro ** 20), math.dot(sd, ro ** 21), math.dot(sd, ro ** 22),
                 math.dot(sd, ro ** 23), math.dot(sd, ro ** 24),
                 math.dot(sd, ro ** 25)]).reshape((l_freq,))

v_14 = tt.stack([math.dot(sd, ro ** 13), math.dot(sd, ro ** 12), math.dot(sd, ro ** 11),
                 math.dot(sd, ro ** 10), math.dot(sd, ro ** 9),
                 math.dot(sd, ro ** 8), math.dot(sd, ro ** 7), math.dot(sd, ro ** 6),
                 math.dot(sd, ro ** 5), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 2), math.dot(sd, ro ** 1),
                 math.dot(sd, ro ** 0), math.dot(sd, ro ** 1), math.dot(sd, ro ** 2),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 5), math.dot(sd, ro ** 6), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 8), math.dot(sd, ro ** 9),
                 math.dot(sd, ro ** 10), math.dot(sd, ro ** 11), math.dot(sd, ro ** 12),
                 math.dot(sd, ro ** 13), math.dot(sd, ro ** 14),
                 math.dot(sd, ro ** 15), math.dot(sd, ro ** 16), math.dot(sd, ro ** 17),
                 math.dot(sd, ro ** 18), math.dot(sd, ro ** 19),
                 math.dot(sd, ro ** 20), math.dot(sd, ro ** 21), math.dot(sd, ro ** 22),
                 math.dot(sd, ro ** 23), math.dot(sd, ro ** 24)]).reshape((l_freq,))

v_15 = tt.stack([math.dot(sd, ro ** 14), math.dot(sd, ro ** 13), math.dot(sd, ro ** 12),
                 math.dot(sd, ro ** 11), math.dot(sd, ro ** 10),
                 math.dot(sd, ro ** 9), math.dot(sd, ro ** 8), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 6), math.dot(sd, ro ** 5),
                 math.dot(sd, ro ** 4), math.dot(sd, ro ** 3), math.dot(sd, ro ** 2),
                 math.dot(sd, ro ** 1),
                 math.dot(sd, ro ** 0), math.dot(sd, ro ** 1), math.dot(sd, ro ** 2),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 5), math.dot(sd, ro ** 6), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 8), math.dot(sd, ro ** 9),
                 math.dot(sd, ro ** 10), math.dot(sd, ro ** 11), math.dot(sd, ro ** 12),
                 math.dot(sd, ro ** 13), math.dot(sd, ro ** 14),
                 math.dot(sd, ro ** 15), math.dot(sd, ro ** 16), math.dot(sd, ro ** 17),
                 math.dot(sd, ro ** 18), math.dot(sd, ro ** 19),
                 math.dot(sd, ro ** 20), math.dot(sd, ro ** 21), math.dot(sd, ro ** 22),
                 math.dot(sd, ro ** 23)]).reshape((l_freq,))

v_16 = tt.stack([math.dot(sd, ro ** 15), math.dot(sd, ro ** 14), math.dot(sd, ro ** 13),
                 math.dot(sd, ro ** 12), math.dot(sd, ro ** 11),
                 math.dot(sd, ro ** 10), math.dot(sd, ro ** 9), math.dot(sd, ro ** 8),
                 math.dot(sd, ro ** 7), math.dot(sd, ro ** 6),
                 math.dot(sd, ro ** 5), math.dot(sd, ro ** 4), math.dot(sd, ro ** 3),
                 math.dot(sd, ro ** 2), math.dot(sd, ro ** 1),
                 math.dot(sd, ro ** 0), math.dot(sd, ro ** 1), math.dot(sd, ro ** 2),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 5), math.dot(sd, ro ** 6), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 8), math.dot(sd, ro ** 9),
                 math.dot(sd, ro ** 10), math.dot(sd, ro ** 11), math.dot(sd, ro ** 12),
                 math.dot(sd, ro ** 13), math.dot(sd, ro ** 14),
                 math.dot(sd, ro ** 15), math.dot(sd, ro ** 16), math.dot(sd, ro ** 17),
                 math.dot(sd, ro ** 18), math.dot(sd, ro ** 19),
                 math.dot(sd, ro ** 20), math.dot(sd, ro ** 21),
                 math.dot(sd, ro ** 22)]).reshape((l_freq,))

v_17 = tt.stack([math.dot(sd, ro ** 16), math.dot(sd, ro ** 15), math.dot(sd, ro ** 14),
                 math.dot(sd, ro ** 13), math.dot(sd, ro ** 12),
                 math.dot(sd, ro ** 11), math.dot(sd, ro ** 10), math.dot(sd, ro ** 9),
                 math.dot(sd, ro ** 8), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 6), math.dot(sd, ro ** 5), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 2), math.dot(sd, ro ** 1),
                 math.dot(sd, ro ** 0), math.dot(sd, ro ** 1), math.dot(sd, ro ** 2),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 5), math.dot(sd, ro ** 6), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 8), math.dot(sd, ro ** 9),
                 math.dot(sd, ro ** 10), math.dot(sd, ro ** 11), math.dot(sd, ro ** 12),
                 math.dot(sd, ro ** 13), math.dot(sd, ro ** 14),
                 math.dot(sd, ro ** 15), math.dot(sd, ro ** 16), math.dot(sd, ro ** 17),
                 math.dot(sd, ro ** 18), math.dot(sd, ro ** 19),
                 math.dot(sd, ro ** 20), math.dot(sd, ro ** 21)]).reshape((l_freq,))

v_18 = tt.stack([math.dot(sd, ro ** 17), math.dot(sd, ro ** 16), math.dot(sd, ro ** 15),
                 math.dot(sd, ro ** 14), math.dot(sd, ro ** 13),
                 math.dot(sd, ro ** 12), math.dot(sd, ro ** 11), math.dot(sd, ro ** 10),
                 math.dot(sd, ro ** 9), math.dot(sd, ro ** 8), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 6), math.dot(sd, ro ** 5), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 2), math.dot(sd, ro ** 1),
                 math.dot(sd, ro ** 0), math.dot(sd, ro ** 1), math.dot(sd, ro ** 2),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 5), math.dot(sd, ro ** 6), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 8), math.dot(sd, ro ** 9),
                 math.dot(sd, ro ** 10), math.dot(sd, ro ** 11), math.dot(sd, ro ** 12),
                 math.dot(sd, ro ** 13), math.dot(sd, ro ** 14),
                 math.dot(sd, ro ** 15), math.dot(sd, ro ** 16), math.dot(sd, ro ** 17),
                 math.dot(sd, ro ** 18), math.dot(sd, ro ** 19),
                 math.dot(sd, ro ** 20)]).reshape((l_freq,))

v_19 = tt.stack([math.dot(sd, ro ** 18), math.dot(sd, ro ** 17), math.dot(sd, ro ** 16),
                 math.dot(sd, ro ** 15), math.dot(sd, ro ** 14), math.dot(sd, ro ** 13),
                 math.dot(sd, ro ** 12), math.dot(sd, ro ** 11), math.dot(sd, ro ** 10),
                 math.dot(sd, ro ** 9), math.dot(sd, ro ** 8), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 6), math.dot(sd, ro ** 5), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 2), math.dot(sd, ro ** 1),
                 math.dot(sd, ro ** 0), math.dot(sd, ro ** 1), math.dot(sd, ro ** 2),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 5), math.dot(sd, ro ** 6), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 8), math.dot(sd, ro ** 9),
                 math.dot(sd, ro ** 10), math.dot(sd, ro ** 11), math.dot(sd, ro ** 12),
                 math.dot(sd, ro ** 13), math.dot(sd, ro ** 14),
                 math.dot(sd, ro ** 15), math.dot(sd, ro ** 16), math.dot(sd, ro ** 17),
                 math.dot(sd, ro ** 18), math.dot(sd, ro ** 19)]).reshape((l_freq,))

v_20 = tt.stack([math.dot(sd, ro ** 19), math.dot(sd, ro ** 18), math.dot(sd, ro ** 17),
                 math.dot(sd, ro ** 16), math.dot(sd, ro ** 15), math.dot(sd, ro ** 14),
                 math.dot(sd, ro ** 13),
                 math.dot(sd, ro ** 12), math.dot(sd, ro ** 11), math.dot(sd, ro ** 10),
                 math.dot(sd, ro ** 9), math.dot(sd, ro ** 8), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 6), math.dot(sd, ro ** 5), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 2), math.dot(sd, ro ** 1),
                 math.dot(sd, ro ** 0), math.dot(sd, ro ** 1), math.dot(sd, ro ** 2),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 5), math.dot(sd, ro ** 6), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 8), math.dot(sd, ro ** 9),
                 math.dot(sd, ro ** 10), math.dot(sd, ro ** 11), math.dot(sd, ro ** 12),
                 math.dot(sd, ro ** 13), math.dot(sd, ro ** 14),
                 math.dot(sd, ro ** 15), math.dot(sd, ro ** 16), math.dot(sd, ro ** 17),
                 math.dot(sd, ro ** 18)]).reshape((l_freq,))

v_21 = tt.stack([math.dot(sd, ro ** 20), math.dot(sd, ro ** 19), math.dot(sd, ro ** 18),
                 math.dot(sd, ro ** 17), math.dot(sd, ro ** 16), math.dot(sd, ro ** 15),
                 math.dot(sd, ro ** 14), math.dot(sd, ro ** 13),
                 math.dot(sd, ro ** 12), math.dot(sd, ro ** 11), math.dot(sd, ro ** 10),
                 math.dot(sd, ro ** 9), math.dot(sd, ro ** 8), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 6), math.dot(sd, ro ** 5), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 2), math.dot(sd, ro ** 1),
                 math.dot(sd, ro ** 0), math.dot(sd, ro ** 1), math.dot(sd, ro ** 2),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 5), math.dot(sd, ro ** 6), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 8), math.dot(sd, ro ** 9),
                 math.dot(sd, ro ** 10), math.dot(sd, ro ** 11), math.dot(sd, ro ** 12),
                 math.dot(sd, ro ** 13), math.dot(sd, ro ** 14),
                 math.dot(sd, ro ** 15), math.dot(sd, ro ** 16),
                 math.dot(sd, ro ** 17)]).reshape((l_freq,))

v_22 = tt.stack([math.dot(sd, ro ** 21), math.dot(sd, ro ** 20), math.dot(sd, ro ** 19),
                 math.dot(sd, ro ** 18), math.dot(sd, ro ** 17), math.dot(sd, ro ** 16),
                 math.dot(sd, ro ** 15), math.dot(sd, ro ** 14), math.dot(sd, ro ** 13),
                 math.dot(sd, ro ** 12), math.dot(sd, ro ** 11), math.dot(sd, ro ** 10),
                 math.dot(sd, ro ** 9), math.dot(sd, ro ** 8), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 6), math.dot(sd, ro ** 5), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 2), math.dot(sd, ro ** 1),
                 math.dot(sd, ro ** 0), math.dot(sd, ro ** 1), math.dot(sd, ro ** 2),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 5), math.dot(sd, ro ** 6), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 8), math.dot(sd, ro ** 9),
                 math.dot(sd, ro ** 10), math.dot(sd, ro ** 11), math.dot(sd, ro ** 12),
                 math.dot(sd, ro ** 13), math.dot(sd, ro ** 14),
                 math.dot(sd, ro ** 15), math.dot(sd, ro ** 16)]).reshape((l_freq,))

v_23 = tt.stack([math.dot(sd, ro ** 22), math.dot(sd, ro ** 21), math.dot(sd, ro ** 20),
                 math.dot(sd, ro ** 19), math.dot(sd, ro ** 18), math.dot(sd, ro ** 17),
                 math.dot(sd, ro ** 16), math.dot(sd, ro ** 15), math.dot(sd, ro ** 14),
                 math.dot(sd, ro ** 13),
                 math.dot(sd, ro ** 12), math.dot(sd, ro ** 11), math.dot(sd, ro ** 10),
                 math.dot(sd, ro ** 9), math.dot(sd, ro ** 8), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 6), math.dot(sd, ro ** 5), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 2), math.dot(sd, ro ** 1),
                 math.dot(sd, ro ** 0), math.dot(sd, ro ** 1), math.dot(sd, ro ** 2),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 5), math.dot(sd, ro ** 6), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 8), math.dot(sd, ro ** 9),
                 math.dot(sd, ro ** 10), math.dot(sd, ro ** 11), math.dot(sd, ro ** 12),
                 math.dot(sd, ro ** 13), math.dot(sd, ro ** 14),
                 math.dot(sd, ro ** 15)]).reshape((l_freq,))

v_24 = tt.stack([math.dot(sd, ro ** 23), math.dot(sd, ro ** 22), math.dot(sd, ro ** 21),
                 math.dot(sd, ro ** 20), math.dot(sd, ro ** 19), math.dot(sd, ro ** 18),
                 math.dot(sd, ro ** 17), math.dot(sd, ro ** 16), math.dot(sd, ro ** 15),
                 math.dot(sd, ro ** 14), math.dot(sd, ro ** 13),
                 math.dot(sd, ro ** 12), math.dot(sd, ro ** 11), math.dot(sd, ro ** 10),
                 math.dot(sd, ro ** 9), math.dot(sd, ro ** 8), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 6), math.dot(sd, ro ** 5), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 2), math.dot(sd, ro ** 1),
                 math.dot(sd, ro ** 0), math.dot(sd, ro ** 1), math.dot(sd, ro ** 2),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 5), math.dot(sd, ro ** 6), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 8), math.dot(sd, ro ** 9),
                 math.dot(sd, ro ** 10), math.dot(sd, ro ** 11), math.dot(sd, ro ** 12),
                 math.dot(sd, ro ** 13), math.dot(sd, ro ** 14)]).reshape((l_freq,))

v_25 = tt.stack([math.dot(sd, ro ** 24), math.dot(sd, ro ** 23), math.dot(sd, ro ** 22),
                 math.dot(sd, ro ** 21), math.dot(sd, ro ** 20), math.dot(sd, ro ** 19),
                 math.dot(sd, ro ** 18), math.dot(sd, ro ** 17), math.dot(sd, ro ** 16),
                 math.dot(sd, ro ** 15), math.dot(sd, ro ** 14), math.dot(sd, ro ** 13),
                 math.dot(sd, ro ** 12), math.dot(sd, ro ** 11), math.dot(sd, ro ** 10),
                 math.dot(sd, ro ** 9), math.dot(sd, ro ** 8), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 6), math.dot(sd, ro ** 5), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 2), math.dot(sd, ro ** 1),
                 math.dot(sd, ro ** 0), math.dot(sd, ro ** 1), math.dot(sd, ro ** 2),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 5), math.dot(sd, ro ** 6), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 8), math.dot(sd, ro ** 9),
                 math.dot(sd, ro ** 10), math.dot(sd, ro ** 11), math.dot(sd, ro ** 12),
                 math.dot(sd, ro ** 13)]).reshape((l_freq,))

v_26 = tt.stack([math.dot(sd, ro ** 25), math.dot(sd, ro ** 24), math.dot(sd, ro ** 23),
                 math.dot(sd, ro ** 22), math.dot(sd, ro ** 21), math.dot(sd, ro ** 20),
                 math.dot(sd, ro ** 19), math.dot(sd, ro ** 18), math.dot(sd, ro ** 17),
                 math.dot(sd, ro ** 16), math.dot(sd, ro ** 15), math.dot(sd, ro ** 14),
                 math.dot(sd, ro ** 13),
                 math.dot(sd, ro ** 12), math.dot(sd, ro ** 11), math.dot(sd, ro ** 10),
                 math.dot(sd, ro ** 9), math.dot(sd, ro ** 8), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 6), math.dot(sd, ro ** 5), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 2), math.dot(sd, ro ** 1),
                 math.dot(sd, ro ** 0), math.dot(sd, ro ** 1), math.dot(sd, ro ** 2),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 5), math.dot(sd, ro ** 6), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 8), math.dot(sd, ro ** 9),
                 math.dot(sd, ro ** 10), math.dot(sd, ro ** 11),
                 math.dot(sd, ro ** 12)]).reshape((l_freq,))

v_27 = tt.stack([math.dot(sd, ro ** 26), math.dot(sd, ro ** 25), math.dot(sd, ro ** 24),
                 math.dot(sd, ro ** 23), math.dot(sd, ro ** 22), math.dot(sd, ro ** 21),
                 math.dot(sd, ro ** 20), math.dot(sd, ro ** 19), math.dot(sd, ro ** 18),
                 math.dot(sd, ro ** 17), math.dot(sd, ro ** 16), math.dot(sd, ro ** 15),
                 math.dot(sd, ro ** 14), math.dot(sd, ro ** 13),
                 math.dot(sd, ro ** 12), math.dot(sd, ro ** 11), math.dot(sd, ro ** 10),
                 math.dot(sd, ro ** 9), math.dot(sd, ro ** 8), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 6), math.dot(sd, ro ** 5), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 2), math.dot(sd, ro ** 1),
                 math.dot(sd, ro ** 0), math.dot(sd, ro ** 1), math.dot(sd, ro ** 2),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 5), math.dot(sd, ro ** 6), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 8), math.dot(sd, ro ** 9),
                 math.dot(sd, ro ** 10), math.dot(sd, ro ** 11)]).reshape((l_freq,))

v_28 = tt.stack([math.dot(sd, ro ** 27), math.dot(sd, ro ** 26), math.dot(sd, ro ** 25),
                 math.dot(sd, ro ** 24), math.dot(sd, ro ** 23), math.dot(sd, ro ** 22),
                 math.dot(sd, ro ** 21), math.dot(sd, ro ** 20), math.dot(sd, ro ** 19),
                 math.dot(sd, ro ** 18), math.dot(sd, ro ** 17), math.dot(sd, ro ** 16),
                 math.dot(sd, ro ** 15), math.dot(sd, ro ** 14), math.dot(sd, ro ** 13),
                 math.dot(sd, ro ** 12), math.dot(sd, ro ** 11), math.dot(sd, ro ** 10),
                 math.dot(sd, ro ** 9), math.dot(sd, ro ** 8), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 6), math.dot(sd, ro ** 5), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 2), math.dot(sd, ro ** 1),
                 math.dot(sd, ro ** 0), math.dot(sd, ro ** 1), math.dot(sd, ro ** 2),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 5), math.dot(sd, ro ** 6), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 8), math.dot(sd, ro ** 9),
                 math.dot(sd, ro ** 10)]).reshape((l_freq,))

v_29 = tt.stack([math.dot(sd, ro ** 28), math.dot(sd, ro ** 27), math.dot(sd, ro ** 26),
                 math.dot(sd, ro ** 25), math.dot(sd, ro ** 24), math.dot(sd, ro ** 23),
                 math.dot(sd, ro ** 22), math.dot(sd, ro ** 21), math.dot(sd, ro ** 20),
                 math.dot(sd, ro ** 19), math.dot(sd, ro ** 18), math.dot(sd, ro ** 17),
                 math.dot(sd, ro ** 16), math.dot(sd, ro ** 15), math.dot(sd, ro ** 14),
                 math.dot(sd, ro ** 13),
                 math.dot(sd, ro ** 12), math.dot(sd, ro ** 11), math.dot(sd, ro ** 10),
                 math.dot(sd, ro ** 9), math.dot(sd, ro ** 8), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 6), math.dot(sd, ro ** 5), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 2), math.dot(sd, ro ** 1),
                 math.dot(sd, ro ** 0), math.dot(sd, ro ** 1), math.dot(sd, ro ** 2),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 5), math.dot(sd, ro ** 6), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 8), math.dot(sd, ro ** 9)]).reshape((l_freq,))

v_30 = tt.stack([math.dot(sd, ro ** 29), math.dot(sd, ro ** 28), math.dot(sd, ro ** 27),
                 math.dot(sd, ro ** 26), math.dot(sd, ro ** 25), math.dot(sd, ro ** 24),
                 math.dot(sd, ro ** 23), math.dot(sd, ro ** 22), math.dot(sd, ro ** 21),
                 math.dot(sd, ro ** 20), math.dot(sd, ro ** 19), math.dot(sd, ro ** 18),
                 math.dot(sd, ro ** 17), math.dot(sd, ro ** 16), math.dot(sd, ro ** 15),
                 math.dot(sd, ro ** 14), math.dot(sd, ro ** 13),
                 math.dot(sd, ro ** 12), math.dot(sd, ro ** 11), math.dot(sd, ro ** 10),
                 math.dot(sd, ro ** 9), math.dot(sd, ro ** 8), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 6), math.dot(sd, ro ** 5), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 2), math.dot(sd, ro ** 1),
                 math.dot(sd, ro ** 0), math.dot(sd, ro ** 1), math.dot(sd, ro ** 2),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 5), math.dot(sd, ro ** 6), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 8)]).reshape((l_freq,))

v_31 = tt.stack([math.dot(sd, ro ** 30), math.dot(sd, ro ** 29), math.dot(sd, ro ** 28),
                 math.dot(sd, ro ** 27), math.dot(sd, ro ** 26), math.dot(sd, ro ** 25),
                 math.dot(sd, ro ** 24), math.dot(sd, ro ** 23), math.dot(sd, ro ** 22),
                 math.dot(sd, ro ** 21), math.dot(sd, ro ** 20), math.dot(sd, ro ** 19),
                 math.dot(sd, ro ** 18), math.dot(sd, ro ** 17), math.dot(sd, ro ** 16),
                 math.dot(sd, ro ** 15), math.dot(sd, ro ** 14), math.dot(sd, ro ** 13),
                 math.dot(sd, ro ** 12), math.dot(sd, ro ** 11), math.dot(sd, ro ** 10),
                 math.dot(sd, ro ** 9), math.dot(sd, ro ** 8), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 6), math.dot(sd, ro ** 5), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 2), math.dot(sd, ro ** 1),
                 math.dot(sd, ro ** 0), math.dot(sd, ro ** 1), math.dot(sd, ro ** 2),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 5), math.dot(sd, ro ** 6), math.dot(sd, ro ** 7)]).reshape(
    (l_freq,))

v_32 = tt.stack([math.dot(sd, ro ** 31), math.dot(sd, ro ** 30), math.dot(sd, ro ** 29),
                 math.dot(sd, ro ** 28), math.dot(sd, ro ** 27), math.dot(sd, ro ** 26),
                 math.dot(sd, ro ** 25), math.dot(sd, ro ** 24), math.dot(sd, ro ** 23),
                 math.dot(sd, ro ** 22), math.dot(sd, ro ** 21), math.dot(sd, ro ** 20),
                 math.dot(sd, ro ** 19), math.dot(sd, ro ** 18), math.dot(sd, ro ** 17),
                 math.dot(sd, ro ** 16), math.dot(sd, ro ** 15), math.dot(sd, ro ** 14),
                 math.dot(sd, ro ** 13),
                 math.dot(sd, ro ** 12), math.dot(sd, ro ** 11), math.dot(sd, ro ** 10),
                 math.dot(sd, ro ** 9), math.dot(sd, ro ** 8), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 6), math.dot(sd, ro ** 5), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 2), math.dot(sd, ro ** 1),
                 math.dot(sd, ro ** 0), math.dot(sd, ro ** 1), math.dot(sd, ro ** 2),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 5), math.dot(sd, ro ** 6)]).reshape((l_freq,))

v_33 = tt.stack([math.dot(sd, ro ** 32), math.dot(sd, ro ** 31), math.dot(sd, ro ** 30),
                 math.dot(sd, ro ** 29), math.dot(sd, ro ** 28), math.dot(sd, ro ** 27),
                 math.dot(sd, ro ** 26), math.dot(sd, ro ** 25), math.dot(sd, ro ** 24),
                 math.dot(sd, ro ** 23), math.dot(sd, ro ** 22), math.dot(sd, ro ** 21),
                 math.dot(sd, ro ** 20), math.dot(sd, ro ** 19), math.dot(sd, ro ** 18),
                 math.dot(sd, ro ** 17), math.dot(sd, ro ** 16), math.dot(sd, ro ** 15),
                 math.dot(sd, ro ** 14), math.dot(sd, ro ** 13),
                 math.dot(sd, ro ** 12), math.dot(sd, ro ** 11), math.dot(sd, ro ** 10),
                 math.dot(sd, ro ** 9), math.dot(sd, ro ** 8), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 6), math.dot(sd, ro ** 5), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 2), math.dot(sd, ro ** 1),
                 math.dot(sd, ro ** 0), math.dot(sd, ro ** 1), math.dot(sd, ro ** 2),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 5)]).reshape((l_freq,))

v_34 = tt.stack([math.dot(sd, ro ** 33), math.dot(sd, ro ** 32), math.dot(sd, ro ** 31),
                 math.dot(sd, ro ** 30), math.dot(sd, ro ** 29), math.dot(sd, ro ** 28),
                 math.dot(sd, ro ** 27), math.dot(sd, ro ** 26), math.dot(sd, ro ** 25),
                 math.dot(sd, ro ** 24), math.dot(sd, ro ** 23), math.dot(sd, ro ** 22),
                 math.dot(sd, ro ** 21), math.dot(sd, ro ** 20), math.dot(sd, ro ** 19),
                 math.dot(sd, ro ** 18), math.dot(sd, ro ** 17), math.dot(sd, ro ** 16),
                 math.dot(sd, ro ** 15), math.dot(sd, ro ** 14), math.dot(sd, ro ** 13),
                 math.dot(sd, ro ** 12), math.dot(sd, ro ** 11), math.dot(sd, ro ** 10),
                 math.dot(sd, ro ** 9), math.dot(sd, ro ** 8), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 6), math.dot(sd, ro ** 5), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 2), math.dot(sd, ro ** 1),
                 math.dot(sd, ro ** 0), math.dot(sd, ro ** 1), math.dot(sd, ro ** 2),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 4)]).reshape((l_freq,))

v_35 = tt.stack([math.dot(sd, ro ** 34), math.dot(sd, ro ** 33), math.dot(sd, ro ** 32),
                 math.dot(sd, ro ** 31), math.dot(sd, ro ** 30), math.dot(sd, ro ** 29),
                 math.dot(sd, ro ** 28), math.dot(sd, ro ** 27), math.dot(sd, ro ** 26),
                 math.dot(sd, ro ** 25), math.dot(sd, ro ** 24), math.dot(sd, ro ** 23),
                 math.dot(sd, ro ** 22), math.dot(sd, ro ** 21), math.dot(sd, ro ** 20),
                 math.dot(sd, ro ** 19), math.dot(sd, ro ** 18), math.dot(sd, ro ** 17),
                 math.dot(sd, ro ** 16), math.dot(sd, ro ** 15), math.dot(sd, ro ** 14),
                 math.dot(sd, ro ** 13),
                 math.dot(sd, ro ** 12), math.dot(sd, ro ** 11), math.dot(sd, ro ** 10),
                 math.dot(sd, ro ** 9), math.dot(sd, ro ** 8), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 6), math.dot(sd, ro ** 5), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 2), math.dot(sd, ro ** 1),
                 math.dot(sd, ro ** 0), math.dot(sd, ro ** 1), math.dot(sd, ro ** 2),
                 math.dot(sd, ro ** 3)]).reshape((l_freq,))

v_36 = tt.stack([math.dot(sd, ro ** 35), math.dot(sd, ro ** 34), math.dot(sd, ro ** 33),
                 math.dot(sd, ro ** 32), math.dot(sd, ro ** 31), math.dot(sd, ro ** 30),
                 math.dot(sd, ro ** 29), math.dot(sd, ro ** 28), math.dot(sd, ro ** 27),
                 math.dot(sd, ro ** 26), math.dot(sd, ro ** 25), math.dot(sd, ro ** 24),
                 math.dot(sd, ro ** 23), math.dot(sd, ro ** 22), math.dot(sd, ro ** 21),
                 math.dot(sd, ro ** 20), math.dot(sd, ro ** 19), math.dot(sd, ro ** 18),
                 math.dot(sd, ro ** 17), math.dot(sd, ro ** 16), math.dot(sd, ro ** 15),
                 math.dot(sd, ro ** 14), math.dot(sd, ro ** 13),
                 math.dot(sd, ro ** 12), math.dot(sd, ro ** 11), math.dot(sd, ro ** 10),
                 math.dot(sd, ro ** 9), math.dot(sd, ro ** 8), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 6), math.dot(sd, ro ** 5), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 2), math.dot(sd, ro ** 1),
                 math.dot(sd, ro ** 0), math.dot(sd, ro ** 1), math.dot(sd, ro ** 2)]).reshape(
    (l_freq,))

v_37 = tt.stack([math.dot(sd, ro ** 36), math.dot(sd, ro ** 35), math.dot(sd, ro ** 34),
                 math.dot(sd, ro ** 33), math.dot(sd, ro ** 32), math.dot(sd, ro ** 31),
                 math.dot(sd, ro ** 30), math.dot(sd, ro ** 29), math.dot(sd, ro ** 28),
                 math.dot(sd, ro ** 27), math.dot(sd, ro ** 26), math.dot(sd, ro ** 25),
                 math.dot(sd, ro ** 24), math.dot(sd, ro ** 23), math.dot(sd, ro ** 22),
                 math.dot(sd, ro ** 21), math.dot(sd, ro ** 20), math.dot(sd, ro ** 19),
                 math.dot(sd, ro ** 18), math.dot(sd, ro ** 17), math.dot(sd, ro ** 16),
                 math.dot(sd, ro ** 15), math.dot(sd, ro ** 14), math.dot(sd, ro ** 13),
                 math.dot(sd, ro ** 12), math.dot(sd, ro ** 11), math.dot(sd, ro ** 10),
                 math.dot(sd, ro ** 9), math.dot(sd, ro ** 8), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 6), math.dot(sd, ro ** 5), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 2), math.dot(sd, ro ** 1),
                 math.dot(sd, ro ** 0), math.dot(sd, ro ** 1)]).reshape((l_freq,))

v_38 = tt.stack([math.dot(sd, ro ** 37), math.dot(sd, ro ** 36), math.dot(sd, ro ** 35),
                 math.dot(sd, ro ** 34), math.dot(sd, ro ** 33), math.dot(sd, ro ** 32),
                 math.dot(sd, ro ** 31), math.dot(sd, ro ** 30), math.dot(sd, ro ** 29),
                 math.dot(sd, ro ** 28), math.dot(sd, ro ** 27), math.dot(sd, ro ** 26),
                 math.dot(sd, ro ** 25), math.dot(sd, ro ** 24), math.dot(sd, ro ** 23),
                 math.dot(sd, ro ** 22), math.dot(sd, ro ** 21), math.dot(sd, ro ** 20),
                 math.dot(sd, ro ** 19), math.dot(sd, ro ** 18), math.dot(sd, ro ** 17),
                 math.dot(sd, ro ** 16), math.dot(sd, ro ** 15), math.dot(sd, ro ** 14),
                 math.dot(sd, ro ** 13),
                 math.dot(sd, ro ** 12), math.dot(sd, ro ** 11), math.dot(sd, ro ** 10),
                 math.dot(sd, ro ** 9), math.dot(sd, ro ** 8), math.dot(sd, ro ** 7),
                 math.dot(sd, ro ** 6), math.dot(sd, ro ** 5), math.dot(sd, ro ** 4),
                 math.dot(sd, ro ** 3), math.dot(sd, ro ** 2), math.dot(sd, ro ** 1),
                 math.dot(sd, ro ** 0)]).reshape((l_freq,))